//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEB.GC.Net.ApiSAP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APISAPEntities1 : DbContext
    {
        public APISAPEntities1()
            : base("name=APISAPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CuerposDeElemento> CuerposDeElementoes { get; set; }
        public virtual DbSet<Elemento> Elementos { get; set; }
        public virtual DbSet<Ensamble_subestacion> Ensamble_subestacions { get; set; }
        public virtual DbSet<Perfile> Perfiles { get; set; }
        public virtual DbSet<Punto> Puntos { get; set; }
        public virtual DbSet<SubestacionSAP> SubestacionSAPs { get; set; }
        public virtual DbSet<elementos_cargado> elementos_cargados { get; set; }
        public virtual DbSet<Carga> Cargas { get; set; }
        public virtual DbSet<CARGAS_DE_CONEXIÓN> CARGAS_DE_CONEXIÓN { get; set; }
        public virtual DbSet<Caso> Casos { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Cargas_Automatica> Cargas_Automaticas { get; set; }
        public virtual DbSet<Casos_de_Combinacione> Casos_de_Combinaciones { get; set; }
        public virtual DbSet<Combinacione> Combinaciones { get; set; }
        public virtual DbSet<Tipos_de_carga> Tipos_de_cargas { get; set; }
        public virtual DbSet<Combinacionespernosoequipos> Combinacionespernosoequipos { get; set; }
        public virtual DbSet<Combinacionesservicio> Combinacionesservicios { get; set; }
        public virtual DbSet<Combinacionesultima> Combinacionesultimas { get; set; }
        public virtual DbSet<resultadosdiseño> resultadosdiseño { get; set; }
    }
}
