//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEB.GC.Net.ApiSAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGAS_DE_CONEXIÓN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARGAS_DE_CONEXIÓN()
        {
            this.Cargas = new HashSet<Carga>();
        }
    
        public int Id { get; set; }
        public string Templa_o_guarda { get; set; }
        public double Peso___kg_ { get; set; }
        public double Corto_Transversal__kg_ { get; set; }
        public double Corto_Longitudinal__kg_ { get; set; }
        public double Viento_Transversal__kg_ { get; set; }
        public double Viento_Longitudinal__kg_ { get; set; }
        public double Tiro__kg_ { get; set; }
        public int Id_Subestacion { get; set; }
        public int Id_Caso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carga> Cargas { get; set; }
        public virtual SubestacionSAP SubestacionSAP { get; set; }
    }
}
