//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEB.GC.Net.ApiSAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargas_Automatica
    {
        public int Id { get; set; }
        public int Id_subestacion { get; set; }
        public int id_caso { get; set; }
        public double Cortante_basal { get; set; }
        public double K_exponente { get; set; }
        public double Velocidad_viento { get; set; }
        public string Tipo_exposicion { get; set; }
        public double Factor_importancia { get; set; }
        public double Factor_topografia { get; set; }
        public double Factor_rafaga { get; set; }
        public double Factor_direccion { get; set; }
        public double R_Porticos { get; set; }
        public double R_Equipos { get; set; }
    
        public virtual Caso Caso { get; set; }
        public virtual SubestacionSAP SubestacionSAP { get; set; }
    }
}
