//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEB.GC.Net.ApiSAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carga
    {
        public int Id { get; set; }
        public int Id_Ensamble { get; set; }
        public int Id_Carga_de_conexion { get; set; }
        public string Templa_o_guarda { get; set; }
        public double Numero_de_fases { get; set; }
        public double Separacion_de_fases { get; set; }
        public double Orientacion { get; set; }
        public string Posicion { get; set; }
        public string Separacion_diferentes { get; set; }
        public double Orden { get; set; }
    
        public virtual CARGAS_DE_CONEXIÓN CARGAS_DE_CONEXIÓN { get; set; }
        public virtual Ensamble_subestacion Ensamble_subestacion { get; set; }
    }
}
