//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEB.GC.Net.ApiSAP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Caso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caso()
        {
            this.Cargas_Automaticas = new HashSet<Cargas_Automatica>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Nombre de Caso")]
        public string nombre_caso { get; set; }
        [Display(Name = "Descripcion de caso")]
        public string descripcion_caso { get; set; }
        public Nullable<int> id_subestacion { get; set; }
    
        public virtual SubestacionSAP SubestacionSAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargas_Automatica> Cargas_Automaticas { get; set; }
    }
}
