//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEB.GC.Net.ApiSAP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Casos_de_Combinacione
    {
        public int Id { get; set; }
        public string Combinacion { get; set; }
        public string Tipo { get; set; }
        public string Caso { get; set; }
        [Display(Name = "Factor de modificacion")]
        public double Factor_de_modificacion { get; set; }
        public int id_subestacion { get; set; }
    }
}
