//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEB.GC.Net.ApiSAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuerposDeElemento
    {
        public int Id_Cuerpo { get; set; }
        public string TipoDeElemento { get; set; }
        public double Ancho_inferior { get; set; }
        public double Largo_Inferior { get; set; }
        public double Ancho_superior { get; set; }
        public double Largo_Superior { get; set; }
        public double Altura { get; set; }
        public string Nivel_de_tension { get; set; }
        public Nullable<int> Id_Elemento { get; set; }
        public string Tipo_de_diagonal { get; set; }
        public int Division_adicional { get; set; }
        public string PerfilMontante { get; set; }
        public string PerfilDiagonarl { get; set; }
        public string PerfilMontanteViga { get; set; }
        public string PerfilDiagonalViga { get; set; }
        public string PerfilCierre { get; set; }
        public string PerfilMontanteCastillete { get; set; }
        public string PerfilDiagonalCastillete { get; set; }
    
        public virtual Elemento Elemento { get; set; }
    }
}
