//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEB.GC.Net.ApiSAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elemento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Elemento()
        {
            this.CuerposDeElementoes = new HashSet<CuerposDeElemento>();
            this.Ensamble_subestacion = new HashSet<Ensamble_subestacion>();
        }
    
        public int Id { get; set; }
        public string Id_Elemento { get; set; }
        public string TipoElemento { get; set; }
        public int NumeroCuerpos { get; set; }
        public int Id_Subestacion { get; set; }
        public string NivelTension { get; set; }
        public int Caso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuerposDeElemento> CuerposDeElementoes { get; set; }
        public virtual SubestacionSAP SubestacionSAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ensamble_subestacion> Ensamble_subestacion { get; set; }
    }
}
