//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEB.GC.Net.ApiSAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int Id { get; set; }
        public string NombreMaterial { get; set; }
        public string TipoMaterial { get; set; }
        public double E_Material { get; set; }
        public double V_Material { get; set; }
        public double T_Material { get; set; }
        public double Fy_Material { get; set; }
        public double Fu_Material { get; set; }
        public double eFy_Material { get; set; }
        public double eFu_Material { get; set; }
    }
}
