//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEB.GC.Net.ApiSAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfile
    {
        public int ID_perfil { get; set; }
        public string Nombre_del_perfil { get; set; }
        public string Material_del_perfil { get; set; }
        public string Tipo_del_perfil { get; set; }
        public string Uso_del_perfil { get; set; }
        public string Nivel_de_tensio { get; set; }
        public double t3___mm_ { get; set; }
        public double t2__mm_ { get; set; }
        public double tf__mm_ { get; set; }
        public double tw__mm_ { get; set; }
        public Nullable<double> t2b__mm_ { get; set; }
        public Nullable<double> tfb__mm_ { get; set; }
        public Nullable<double> Area___mm2_ { get; set; }
        public Nullable<double> Constante_torsional__mm4_ { get; set; }
        public Nullable<double> I33__mm4_ { get; set; }
        public Nullable<double> I22___mm4_ { get; set; }
        public Nullable<double> I23___mm4_ { get; set; }
        public Nullable<double> AS2__mm2_ { get; set; }
        public Nullable<double> AS3__mm2_ { get; set; }
        public Nullable<double> S33__mm3_ { get; set; }
        public Nullable<double> S22__mm3_ { get; set; }
        public Nullable<double> Z33__mm3_ { get; set; }
        public Nullable<double> Z22__mm3_ { get; set; }
        public Nullable<double> R33__mm_ { get; set; }
        public Nullable<double> R22__mm_ { get; set; }
        public Nullable<double> Lmax__mm_ { get; set; }
        public Nullable<double> Lmin__mm_ { get; set; }
        public Nullable<double> Rz__mm_ { get; set; }
        public Nullable<double> Ru__mm_ { get; set; }
        public Nullable<int> id_subestacion { get; set; }
    }
}
