//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEB.GC.Net.ApiSAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resultadosdiseño
    {
        public int Id { get; set; }
        public string Elemento { get; set; }
        public string Seccion { get; set; }
        public double Relacion { get; set; }
        public string tipo_de_relacion { get; set; }
        public string Mensaje_de_error { get; set; }
        public int caso { get; set; }
    }
}
