//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEB.GC.Net.ApiSAP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SubestacionSAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubestacionSAP()
        {
            this.Elementos = new HashSet<Elemento>();
            this.CARGAS_DE_CONEXIÓN = new HashSet<CARGAS_DE_CONEXIÓN>();
            this.Casos = new HashSet<Caso>();
            this.Cargas_Automaticas = new HashSet<Cargas_Automatica>();
        }
    
        public int Id { get; set; }
        public string Revisor { get; set; }
        public string Aprobador { get; set; }
        [Display(Name = "Nombre de proyecto")]
        public string NombreProyecto { get; set; }
        [Display(Name = "Nombre de subestacion")]
        public string NombreSubestacion { get; set; }
        [Display(Name = "Nombre del modelo")]
        public string NombreModelo { get; set; }

        public Nullable<int> Id_Subestacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Elemento> Elementos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARGAS_DE_CONEXIÓN> CARGAS_DE_CONEXIÓN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caso> Casos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargas_Automatica> Cargas_Automaticas { get; set; }
    }
}
